import "/node_modules/boxicons/css/boxicons.min.css"
import localFont from "next/font/local";
import "./globals.css";

import {NextUIProvider} from "@nextui-org/react";

export const comicSans = localFont({
  src: "./fonts/ComicSans.ttf",
  variable: "--font-comic-sans",
  weight: "100 900",
})

export const metadata = {
  title: "ServiceCompranyApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${comicSans.variable} antialiased`}>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
